#!/bin/bash
if [ $# -lt 2 ]
then
	echo "Usage: gddb [rules] [facts] [styles]"
	exit
fi

python parsedlv.py $1 > dlv_aux_rules
dlv dlv_aux_rules $2 > dlv_out
if [ $# -eq 3 ]
then
	python gddb.py parse_map.p dlv_out $3 
else
	python gddb.py parse_map.p dlv_out  
fi
rm *.pyc
