#!/bin/bash
#======================================================================
# GDDB: Graphical Datalog Debugger 
# Author: Jade Koskela <jtkoskela@ucdavis.edu>
# http://github.com/jkoskela/gddb
# Main script for gddb.
#
#======================================================================

if [ $# -lt 2 ]
then
	echo "Usage: gddb [rules] [facts] [styles]"
	exit
fi

python parsedlv.py $1 > dlv_aux_rules 2> err
ERROR_SIZE=$(stat -c %s err)
if [ $ERROR_SIZE != 0 ]
then	
	echo "There were parsing errors."
	exit
fi

./dlv dlv_aux_rules $2 > dlv_out
if [ $# -eq 3 ]
then
	python gddb.py parse_map.p dlv_out $3 
else
	python gddb.py parse_map.p dlv_out  
fi
rm *.pyc
